version: '3'
services:
  dhcpd:
    restart: always
    image: lnls/dhcpd
    container_name: dhcpd
    command: ["eno1"]
    volumes:
      - ./data:/data
    logging:
      options:
        max-size: 50m
    network_mode: "host"
    dns: 10.128.255.7
    dns_search: lnls-sirius.com.br
